title: <p align="center"> Sunil Sharma </p>
logo: /assets/img/Personal Image.png
description: 
<p align="center">
  <a href="https://www.linkedin.com/in/sunil-sharma-5374b126/">LinkedIn</a> |
  <a href="https://github.com/sunil08-mits/">GitHub</a>
  
  <br>   
  Data Science Learner.
  Working in SAP Lab India Pvt Ltd as an Architect.
  Currently pursuing AI & ML course from IIIT-B.
  <br>
  </p>
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
